/**
 * Legal pages the store may need. They are created as EMPTY DRAFTS: nothing is
 * shown to customers until the owner writes real text (ideally reviewed by a
 * lawyer) and ticks "Published". No legal wording is generated by the app.
 */
export const POLICY_PAGES = [
  { slug: "privacy-policy", title: "Privacy Policy" },
  { slug: "terms-of-service", title: "Terms of Service" },
  { slug: "shipping-policy", title: "Shipping Policy" },
  { slug: "return-policy", title: "Return & Exchange Policy" },
] as const;

export function isPolicySlug(slug: string): boolean {
  return POLICY_PAGES.some((page) => page.slug === slug);
}
